package com.meera.dbservice.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.meera.dbservice.model.Field;
import com.meera.dbservice.service.FieldLocalServiceUtil;

/**
 * The extended model base implementation for the Field service. Represents a row in the &quot;LS_Field&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FieldImpl}.
 * </p>
 *
 * @author LiferayFarmer
 * @see FieldImpl
 * @see com.meera.dbservice.model.Field
 * @generated
 */
public abstract class FieldBaseImpl extends FieldModelImpl implements Field {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a field model instance should use the {@link Field} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FieldLocalServiceUtil.addField(this);
        } else {
            FieldLocalServiceUtil.updateField(this);
        }
    }
}
