package com.meera.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Area service. Represents a row in the &quot;LS_Area&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.meera.dbservice.model.impl.AreaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.meera.dbservice.model.impl.AreaImpl}.
 * </p>
 *
 * @author LiferayFarmer
 * @see Area
 * @see com.meera.dbservice.model.impl.AreaImpl
 * @see com.meera.dbservice.model.impl.AreaModelImpl
 * @generated
 */
public interface AreaModel extends BaseModel<Area> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a area model instance should use the {@link Area} interface instead.
     */

    /**
     * Returns the primary key of this area.
     *
     * @return the primary key of this area
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this area.
     *
     * @param primaryKey the primary key of this area
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the area ID of this area.
     *
     * @return the area ID of this area
     */
    public long getAreaId();

    /**
     * Sets the area ID of this area.
     *
     * @param areaId the area ID of this area
     */
    public void setAreaId(long areaId);

    /**
     * Returns the area name of this area.
     *
     * @return the area name of this area
     */
    @AutoEscape
    public String getAreaName();

    /**
     * Sets the area name of this area.
     *
     * @param areaName the area name of this area
     */
    public void setAreaName(String areaName);

    /**
     * Returns the archive of this area.
     *
     * @return the archive of this area
     */
    public int getArchive();

    /**
     * Sets the archive of this area.
     *
     * @param archive the archive of this area
     */
    public void setArchive(int archive);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.meera.dbservice.model.Area area);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.meera.dbservice.model.Area> toCacheModel();

    @Override
    public com.meera.dbservice.model.Area toEscapedModel();

    @Override
    public com.meera.dbservice.model.Area toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
