package com.meera.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Farmer service. Represents a row in the &quot;LS_Farmer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.meera.dbservice.model.impl.FarmerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.meera.dbservice.model.impl.FarmerImpl}.
 * </p>
 *
 * @author LiferayFarmer
 * @see Farmer
 * @see com.meera.dbservice.model.impl.FarmerImpl
 * @see com.meera.dbservice.model.impl.FarmerModelImpl
 * @generated
 */
public interface FarmerModel extends BaseModel<Farmer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a farmer model instance should use the {@link Farmer} interface instead.
     */

    /**
     * Returns the primary key of this farmer.
     *
     * @return the primary key of this farmer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this farmer.
     *
     * @param primaryKey the primary key of this farmer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the farmer ID of this farmer.
     *
     * @return the farmer ID of this farmer
     */
    public long getFarmerId();

    /**
     * Sets the farmer ID of this farmer.
     *
     * @param farmerId the farmer ID of this farmer
     */
    public void setFarmerId(long farmerId);

    /**
     * Returns the name of this farmer.
     *
     * @return the name of this farmer
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this farmer.
     *
     * @param name the name of this farmer
     */
    public void setName(String name);

    /**
     * Returns the organization_legal of this farmer.
     *
     * @return the organization_legal of this farmer
     */
    @AutoEscape
    public String getOrganization_legal();

    /**
     * Sets the organization_legal of this farmer.
     *
     * @param organization_legal the organization_legal of this farmer
     */
    public void setOrganization_legal(String organization_legal);

    /**
     * Returns the i t n of this farmer.
     *
     * @return the i t n of this farmer
     */
    public long getITN();

    /**
     * Sets the i t n of this farmer.
     *
     * @param ITN the i t n of this farmer
     */
    public void setITN(long ITN);

    /**
     * Returns the i e c of this farmer.
     *
     * @return the i e c of this farmer
     */
    public long getIEC();

    /**
     * Sets the i e c of this farmer.
     *
     * @param IEC the i e c of this farmer
     */
    public void setIEC(long IEC);

    /**
     * Returns the p s r n of this farmer.
     *
     * @return the p s r n of this farmer
     */
    public long getPSRN();

    /**
     * Sets the p s r n of this farmer.
     *
     * @param PSRN the p s r n of this farmer
     */
    public void setPSRN(long PSRN);

    /**
     * Returns the area_registration of this farmer.
     *
     * @return the area_registration of this farmer
     */
    @AutoEscape
    public String getArea_registration();

    /**
     * Sets the area_registration of this farmer.
     *
     * @param area_registration the area_registration of this farmer
     */
    public void setArea_registration(String area_registration);

    /**
     * Returns the area_fields of this farmer.
     *
     * @return the area_fields of this farmer
     */
    @AutoEscape
    public String getArea_fields();

    /**
     * Sets the area_fields of this farmer.
     *
     * @param area_fields the area_fields of this farmer
     */
    public void setArea_fields(String area_fields);

    /**
     * Returns the date_registration of this farmer.
     *
     * @return the date_registration of this farmer
     */
    @AutoEscape
    public String getDate_registration();

    /**
     * Sets the date_registration of this farmer.
     *
     * @param date_registration the date_registration of this farmer
     */
    public void setDate_registration(String date_registration);

    /**
     * Returns the archive of this farmer.
     *
     * @return the archive of this farmer
     */
    public int getArchive();

    /**
     * Sets the archive of this farmer.
     *
     * @param archive the archive of this farmer
     */
    public void setArchive(int archive);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.meera.dbservice.model.Farmer farmer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.meera.dbservice.model.Farmer> toCacheModel();

    @Override
    public com.meera.dbservice.model.Farmer toEscapedModel();

    @Override
    public com.meera.dbservice.model.Farmer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
