package com.meera.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Field service. Represents a row in the &quot;LS_Field&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.meera.dbservice.model.impl.FieldModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.meera.dbservice.model.impl.FieldImpl}.
 * </p>
 *
 * @author LiferayFarmer
 * @see Field
 * @see com.meera.dbservice.model.impl.FieldImpl
 * @see com.meera.dbservice.model.impl.FieldModelImpl
 * @generated
 */
public interface FieldModel extends BaseModel<Field> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a field model instance should use the {@link Field} interface instead.
     */

    /**
     * Returns the primary key of this field.
     *
     * @return the primary key of this field
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this field.
     *
     * @param primaryKey the primary key of this field
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the field ID of this field.
     *
     * @return the field ID of this field
     */
    public long getFieldId();

    /**
     * Sets the field ID of this field.
     *
     * @param fieldId the field ID of this field
     */
    public void setFieldId(long fieldId);

    /**
     * Returns the area ID of this field.
     *
     * @return the area ID of this field
     */
    public long getAreaId();

    /**
     * Sets the area ID of this field.
     *
     * @param areaId the area ID of this field
     */
    public void setAreaId(long areaId);

    /**
     * Returns the field name of this field.
     *
     * @return the field name of this field
     */
    @AutoEscape
    public String getFieldName();

    /**
     * Sets the field name of this field.
     *
     * @param fieldName the field name of this field
     */
    public void setFieldName(String fieldName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.meera.dbservice.model.Field field);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.meera.dbservice.model.Field> toCacheModel();

    @Override
    public com.meera.dbservice.model.Field toEscapedModel();

    @Override
    public com.meera.dbservice.model.Field toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
